import type { Metadata } from 'next';
import {
    Noto_Sans,
    Noto_Serif,
    Pacifico,
    Source_Code_Pro,
} from 'next/font/google';
import './globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import { cookies } from 'next/headers';
import { ThemeProvider } from '@/components/theme-provider';
import { FontProvider } from '@/components/font-provider';

const notoSans = Noto_Sans({
    variable: '--font-sans',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const notoSerif = Noto_Serif({
    variable: '--font-serif',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const sourceCodePro = Source_Code_Pro({
    variable: '--font-monospace',
    subsets: ['latin'],
    weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

const pacifico = Pacifico({
    variable: '--font-pacifico',
    subsets: ['latin'],
    weight: ['400'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const sidebarState = cookieStore.get('sidebar_state')?.value;

    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${notoSans.variable} ${notoSerif.variable} ${sourceCodePro.variable} ${pacifico.variable} antialiased`}>
                <FontProvider defaultFont="sans">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange>
                        <SidebarProvider defaultOpen={sidebarState === 'true'}>
                            {children}
                        </SidebarProvider>
                    </ThemeProvider>
                </FontProvider>
            </body>
        </html>
    );
}
